name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './backend/go.mod'
        check-latest: true

    - name: Go tidy to ensure no untidy changes have been committed
      run: go mod tidy && git diff --exit-code
      working-directory: ./backend
  
    - name: Install dependencies
      run: go mod download
      working-directory: ./backend

    - name: Verify the dependencies
      run: go mod verify
      working-directory: ./backend

    - name: Run lint
      run: go fmt ./...
      working-directory: ./backend

    - name: Run tests
      run: go test ./...
      working-directory: ./backend

  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend/words

    - name: Run lint
      run: npm run lint
      working-directory: ./frontend